name: swifty_companion
description: "Swifty-Companion is a profile viewer for 42 students."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  oauth2: ^2.0.3
  url_launcher: ^6.3.1
  app_links: ^6.3.3
  flutter_svg: ^2.0.17
  percent_indicator: ^4.2.4
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - .env